name: CI

on: [push, pull_request]

jobs:
  test:
    name: JEST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:  |
          yarn install
          yarn test

  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v3.0.0
        if: ${{ github.event_name == 'push' }}
        with:
          slack_channel_id: CNMFKCYCT
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
